version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/cityfinance/cityfinance-node-api
hooks:
  BeforeInstall:
    - location: scripts/before_intall.sh
      timeout: 300
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300