// Json structure.
let keyDetailsForm1 = {
    nameOfUlb: {
        formFieldType: 'text',
        key: 'nameOfUlb',
        displayPriority: '1',
        label: 'Name of ULB',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    nameOfState: {
        formFieldType: 'text',
        key: 'nameOfState',
        displayPriority: '2',
        label: 'Name of State/Union Territory ',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    pop2011: {
        formFieldType: 'number',
        key: 'pop2011',
        displayPriority: '3',
        label: 'Population as per Census 2011',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: 0,
        max: 1000000,
        decimal: 0
    },
    popApril2024: {
        formFieldType: 'number',
        key: 'popApril2024',
        displayPriority: '4',
        label: 'Population as per 01 April 2024',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: 0,
        max: 1000000,
        decimal: 0
    },
    areaOfUlb: {
        formFieldType: 'number',
        key: 'areaOfUlb',
        displayPriority: '5',
        label: 'Area of the ULB (in Sq. Km.)',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: 0.1,
        max: 1000,
        decimal: 2
    },
    yearOfElection: {
        formFieldType: 'dropdown',
        options: ["2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024"],
        showInputBox: "",
        key: 'yearOfElection',
        displayPriority: '6',
        label: "Which is the latest year when ULB's election was held?",
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    isElected: {
        formFieldType: 'radio',
        options: ['Yes', 'No'],
        key: 'isElected',
        displayPriority: '7',
        label: 'Is the elected body in place as on 01 April 2024?',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    yearOfConstitution: {
        formFieldType: 'dropdown',
        options: ["Before 2015-16", "In 2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21", "2021-22", "2022-23"],
        showInputBox: "",
        key: 'yearOfConstitution',
        displayPriority: '8',
        label: 'In which year was the ULB constituted?',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    sourceOfFd: {
        formFieldType: 'dropdown',
        options: ["Accounts Finalized & Audited", "Accounts Finalized but Not Audited", "Accounts not Finalized - Provisional data"],
        showInputBox: "",
        key: 'sourceOfFd',
        displayPriority: '*',
        label: 'Please select the source of Financial Data',
        info: '',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    taxRevenue: {
        formFieldType: 'number',
        key: 'taxRevenue',
        displayPriority: '1.1',
        label: 'Tax Revenue',
        info: 'Tax revenue shall include property, water, drainage, sewerage,professional, entertainment and advertisment tax and all other tax revenues.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    feeAndUserCharges: {
        formFieldType: 'number',
        key: 'feeAndUserCharges',
        displayPriority: '1.2',
        label: 'Fee and User Charges',
        info: 'Fees & user charges shall include Water supply, Fees & Sanitation / Sewerage, Garbage collection / Solid waste management, and all other fees & user charges.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    interestIncome: {
        formFieldType: 'number',
        key: 'interestIncome',
        displayPriority: '1.3',
        label: 'Interest Income',
        info: 'Interest income shall include sale from assets, land and other assets.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherIncome: {
        formFieldType: 'number',
        key: 'otherIncome',
        displayPriority: '1.4',
        label: 'Other Income',
        info: 'Other income shall include sale & hire charges, income from investments,interest earned, etc.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    totOwnRevenue: {
        formFieldType: 'number',
        key: 'totOwnRevenue',
        displayPriority: '1',
        label: 'Total Own Revenue',
        info: 'Total own revenue shall include tax revenue, fees & user charges, interest income, and other income.',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['1.1', '1.2', '1.3', '1.4'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    centralGrants: {
        formFieldType: 'number',
        key: 'centralGrants',
        displayPriority: '2.1',
        label: "Grants for Centre's Initiatives ",
        info: "These grants shall include Union Finance Commission grants, Grants received for Centrally Sponsored Schemes (including state's matching share).",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherGrants: {
        formFieldType: 'number',
        key: 'otherGrants',
        displayPriority: '2.2',
        label: "Other Grants (including State's grants)",
        info: 'These grants shall include State Finance Commission grants, Other State ,Grants, Other grants etc.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    totalGrants: {
        formFieldType: 'number',
        key: 'totalGrants',
        displayPriority: '2',
        label: 'Total Grants',
        info: '',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['2.1', '2.2'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    assignedRevAndCom: {
        formFieldType: 'number',
        key: 'assignedRevAndCom',
        displayPriority: '3',
        label: 'Assigned Revenue and Compensation',
        info: 'Assigned Revenue includes share in the revenues of the state government ,allocated to the ULB. This includes Entertainment Tax, Duty on Transfer of Properties,etc.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherRevenue: {
        formFieldType: 'number',
        key: 'otherRevenue',
        displayPriority: '4',
        label: 'Other Revenue',
        info: 'Other Revenue shall include any other sources of revenue except own ,revenue, assigned revenue and grants',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    totalRevenue: {
        formFieldType: 'number',
        key: 'totalRevenue',
        displayPriority: '5',
        label: 'Total Revenues',
        info: 'Total Revenue is the sum of: (a) tax revenues, (b) non-tax revenues, (c) assigned (shared) revenue, (c) grants-in-aid, (d) other receipts, etc.',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['1', '2', '3', '4'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    establishmentExp: {
        formFieldType: 'number',
        key: 'establishmentExp',
        displayPriority: '6.1',
        label: 'Establishment Expenses',
        info: 'Expenses directly incurred on human resources of the ULB such as ,wages, and employee benefits such as retirement and pensions are called establishment expenses',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    oAndmExp: {
        formFieldType: 'number',
        key: 'oAndmExp',
        displayPriority: '6.2',
        label: 'Operation and Maintenance Expenditure',
        info: 'Operation and Maintenance Expenditure shall include O&M expense on water supply + O&M expense on sanitation / sewerage + All other O&M expenses.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    interestAndfinacialChar: {
        formFieldType: 'number',
        key: 'interestAndfinacialChar',
        displayPriority: '6.3',
        label: 'Interest and Finance Charges',
        info: 'Interest and Finance Charges shall include Interest on Loans from Central Govt, State Govt, International agencies, govt bodies, banks, bank charges and other financial expenses, etc.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherRevenueExp: {
        formFieldType: 'number',
        key: 'otherRevenueExp',
        displayPriority: '6.4',
        label: 'Other Revenue Expenditure',
        info: 'Other expenses shall include programme expenses, revenue grants, contributions & subsidies.',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    totalRevenueExp: {
        formFieldType: 'number',
        key: 'totalRevenueExp',
        displayPriority: '6',
        label: 'Total Revenue Expenditure',
        info: 'Total expenditure shall include establishment expenses, operations & maintenance + interest & finance charges and other expenditure.',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['6.1', '6.2', '6.3', '6.4'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    capExp: {
        formFieldType: 'number',
        key: 'capExp',
        displayPriority: '7',
        label: 'Capital Expenditure',
        info: 'Capital Expenditure = (Closing Balance Gross Block + Closing Balance Capital Work in Progress) - (Opening Balance Gross Block + Opening Balance Capital Work in Progress)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    totalExp: {
        formFieldType: 'number',
        key: 'totalExp',
        displayPriority: '8',
        label: 'Total Expenditure',
        info: 'Total Expenditure = Revenue Expenditure + Capital Expenditure',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['6', '7'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    grossBorrowing: {
        formFieldType: 'number',
        key: 'grossBorrowing',
        displayPriority: '9',
        label: 'Gross Borrowings',
        info: 'Gross Borrowings = Sum of All Secured and Unsecured Loans',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    accSystem: {
        formFieldType: 'radio',
        options: [
            'Cash Basis of Accounting',
            'Accrual Basis of Accounting',
            'Modified Cash/ Accrual Accounting'
        ],
        showInputBox: '',
        key: 'accSystem',
        displayPriority: '1',
        label: 'What is the accounting system being followed by the ULB?',
        info: {
            "Cash basis of accounting": "Revenues and expenses are recognised/recorded when the related cash receipts or cash payments take place.",
            "Accrual basis of accounting": "Revenues and expneses are  recognised/recorded as they are earned or incurred (and not as money is received or paid) and recorded in the financial statements of the periods to which they relate.",
            "Modified": "Revenues are recognized/recorded when cash is received and expenses when they are paid, with the exception of capitalizing long-term assets and recording their related depreciation."
        },
        required: true,
        year: 1
    },
    accProvision: {
        formFieldType: 'radio',
        options: [
            'National Municipal Accounting Manual',
            'State-specific Municipal Accounting Manual',
            'Other (Please specify)'
        ],
        showInputBox: 'Other (Please specify)',
        key: 'accProvision',
        displayPriority: '2',
        label: 'What accounting provisions or framework does the ULB follow?',
        info: '',
        required: true,
        year: 1
    },
    accInCashBasis: {
        formFieldType: 'radio',
        options: ['Yes (Please specify)', 'No'],
        showInputBox: 'Yes (Please specify)',
        key: 'accInCashBasis',
        displayPriority: '3',
        label: 'Are there any accounts/books/registers maintained in cash basis?',
        info: 'Types of registers maintained: cash book, receipt register, register of bills for payment, collection register, deposit register, register of fixed assets etc.',
        required: true,
        year: 1
    },
    fsTransactionRecord: {
        formFieldType: 'radio',
        options: ['Yes', 'No'],
        showInputBox: '',
        key: 'fsTransactionRecord',
        displayPriority: '4',
        label: 'Does the ULB initially record transactions on a cash basis and subsequently prepare accrual accounts for consolidation of financial statements?',
        info: '',
        required: true,
        year: 1
    },
    fsPreparedBy: {
        formFieldType: 'radio',
        options: [
            'Internally (by Accounts Department)',
            'External Chartered Accountants',
            'Both'
        ],
        showInputBox: '',
        key: 'fsPreparedBy',
        displayPriority: '5',
        label: "Are the Financial Statements prepared internally by the ULB's accounting department, or are they compiled by an external Chartered Accountant?",
        info: '',
        required: true,
        year: 1
    },
    revReceiptRecord: {
        formFieldType: 'radio',
        options: [
            'Recorded when cash is received',
            'Recorded when they are accrued',
            'Both (Please specify which transactions are recognised in accrual basis)'
        ],
        showInputBox: 'Both (Please specify which transactions are recognised in accrual basis)',
        key: 'revReceiptRecord',
        displayPriority: '6',
        label: 'Is the revenue receipt recorded when the cash is received or when it is accrued/event occurs?',
        info: '',
        required: true,
        year: 1
    },
    expRecord: {
        formFieldType: 'radio',
        options: [
            'Recorded when cash is paid',
            'Recorded when they are accrued',
            'Both (Please specify which transactions are recognised in accrual basis)'
        ],
        showInputBox: 'Both (Please specify which transactions are recognised in accrual basis)',
        key: 'expRecord',
        displayPriority: '7',
        label: 'Is the expense recorded when it is paid or when it is incurred/event occurs?',
        info: '',
        required: true,
        year: 1
    },
    accSoftware: {
        formFieldType: 'radio',
        options: [
            'Centralized system provided by the State',
            'Standalone software',
            'Tally',
            'Other (Please specify)',
            'None'
        ],
        showInputBox: 'Other (Please specify)',
        key: 'accSoftware',
        displayPriority: '8',
        label: 'What accounting software is currently in use by the ULB?',
        info: '',
        required: true,
        year: 1
    },
    onlineAccSysIntegrate: {
        formFieldType: 'radio',
        options: [
            'Yes (Please specify which all system, e.g., tax collection, payroll, asset management)',
            'No'
        ],
        showInputBox: 'Yes (Please specify which all system, e.g., tax collection, payroll, asset management)',
        key: 'onlineAccSysIntegrate',
        displayPriority: '9',
        label: 'Does the online accounting system integrate seamlessly with other municipal systems?',
        info: '',
        required: true,
        year: 1
    },
    muniAudit: {
        formFieldType: 'radio',
        options: ['External Chartered Accountant (CA)', 'State Audit Department'],
        showInputBox: '',
        key: 'muniAudit',
        displayPriority: '10',
        label: 'Who does the municipal audit of financial statements ?',
        info: '',
        required: true,
        year: 1
    },
    totSanction: {
        formFieldType: 'number',
        key: 'totSanction',
        displayPriority: '11',
        label: 'What is the total sanctioned posts for finance & accounts related positions?',
        info: '',
        required: true,
        year: 1,
        max: 9999,
        min: 0,
        decimal: 0,
        validation: '',
        logic: '',
    },
    totVacancy: {
        formFieldType: 'number',
        key: 'totVacancy',
        displayPriority: '12',
        label: 'What is the total vacancy across finance & accounts related positions?',
        info: '',
        required: true,
        year: 1,
        max: 9999,
        min: 0,
        decimal: 0,
        validation: 'lessThan',
        logic: '11',
    },
    accPosition: {
        formFieldType: 'number',
        key: 'accPosition',
        displayPriority: '13',
        label: 'How many finance & accounts related positions currently are filled on contractual basis or outsourced?',
        info: '',
        required: true,
        year: 1,
        max: 9999,
        min: 0,
        decimal: 0,
        validation: '',
        logic: '',
    },
    auditedAnnualFySt: {
        instruction: [
            { "instruction": "Annual Financial Statement should include: Income and Expenditure Statement, Balance Sheet, Schedules to IES and BS, Auditor's Report and if available Receipts & Payments Statement." },
            { "instruction": " All documents pertaining to a specific financial year should be combined into a single PDF before uploading & should not exceed 20 MB." },
            { "instruction": "Please use the following format for naming the documents to be uploaded: nameofthedocument_FY_ULB Name. || Example: Annual accounts_15-16_Jaipur municipal corporation" },
        ],
        formFieldType: 'file',
        key: 'auditedAnnualFySt',
        displayPriority: '',
        label: 'Copy of Audited Annual Financial Statements preferably in English',
        info: '',
        required: true,
        year: 8,
        max: 5,
        min: 0,
        decimal: 0
    },
}
let keyDetailsForm2 = {
    yearOfSlb: {
        formFieldType: 'dropdown',
        options: ["2015-16", "2016-17", "2017-18", "2018-19", "2019-20", "2020-21", "2021-22", "2022-23"],
        showInputBox: "",
        key: 'yearOfSlb',
        displayPriority: '9',
        label: 'From which year is Service Level Benchmark data available?',
        info: '',
        required: true,
        year: 1,
        validation: '',
        logic: '',
        min: "",
        max: "",
        decimal: ""
    },
    pTax: {
        formFieldType: 'number',
        key: 'pTax',
        displayPriority: '1.1.1',
        label: 'Property Tax',
        info: 'Property tax shall include only proprty tax levied on residential and commercial properties',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherTax: {
        formFieldType: 'number',
        key: 'otherTax',
        displayPriority: '1.1.2',
        label: 'Other Tax',
        info: 'Other Tax shall include any tax other than property tax levied by the ULB',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    rentalIncome: {
        formFieldType: 'number',
        key: 'rentalIncome',
        displayPriority: '1.5',
        label: 'Rental Income from Municipal Properties',
        info: 'Rental Income shall include rental incomes earned out of shopping complexes, markets, office buildings, etc',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    centralSponsoredScheme: {
        formFieldType: 'number',
        key: 'centralSponsoredScheme',
        displayPriority: '2.1.1',
        label: "Centrally Sponsored Schemes (Total Centre and State Share)",
        info: "Centrally Sponsored Scheme shall include  Grants received for Centrally Sponsored Schemes (including state's matching share)",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    unionFinanceGrants: {
        formFieldType: 'number',
        key: 'unionFinanceGrants',
        displayPriority: '2.1.2',
        label: "Union Finance Commission Grants",
        info: "Union Finance Commission Grants shall include Union Finance Commission grants",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    sfcGrants: {
        formFieldType: 'number',
        key: 'sfcGrants',
        displayPriority: '2.2.1',
        label: "State Finance Commission Devolution and Grants",
        info: "State Finance Commission Devolution and Grants shall include State Finance Commission grants",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    grantsOtherThanSfc: {
        formFieldType: 'number',
        key: 'grantsOtherThanSfc',
        displayPriority: '2.2.2',
        label: "Grants from State (other than SFC)",
        info: "Grants from State shall include  Other State Grants (excluding State Finance Commission grants)",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    grantsWithoutState: {
        formFieldType: 'number',
        key: 'grantsWithoutState',
        displayPriority: '2.2.3',
        label: "Other grants",
        info: "Other Grants shall include any other grants received by the ULB",
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    salaries: {
        formFieldType: 'number',
        key: 'salaries',
        displayPriority: '6.1.1',
        label: 'Salaries, Bonus and Wages',
        info: 'Salaries, Bonus & Wages shall include expenses directly incurred on human resources of the ULB such as wages, salaries and bonus',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    pension: {
        formFieldType: 'number',
        key: 'pension',
        displayPriority: '6.1.2',
        label: 'Pension',
        info: 'Pension shall include expenses directly incurred on human resources of the ULB such as pension',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    otherExp: {
        formFieldType: 'number',
        key: 'otherExp',
        displayPriority: '6.1.3',
        label: 'Others',
        info: 'Others shall include any other expenses directly incurred on human resources of the ULB',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    adExp: {
        formFieldType: 'number',
        key: 'adExp',
        displayPriority: '6.5',
        label: 'Administrative Expenses',
        info: 'Administrative Expenses shall include Indirect expenses  which relate to the ULB as a whole, such as Rents, Rates & Taxes, Office maintenance, Communications, Books & periodicals, Printing & Stationary, Travel Expenditure, Law Charges etc. ',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: 0
    },
    centralStateBorrow: {
        formFieldType: 'number',
        key: 'centralStateBorrow',
        displayPriority: '9.1',
        label: 'Central and State Government',
        info: 'Central and State Government includes the sum of All Secured and Unsecured Loans from Central and State Government',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    bonds: {
        formFieldType: 'number',
        key: 'bonds',
        displayPriority: '9.2',
        label: 'Bonds',
        info: 'Bonds includes the sum of bond amounts issued by the ULB',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    bankAndFinancial: {
        formFieldType: 'number',
        key: 'bankAndFinancial',
        displayPriority: '9.3',
        label: 'Banks and Financial Institutions',
        info: 'Banks and Financial Institutions includes the sum of all secured and Unsecured Loans from banks and other financial institution',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    otherBorrowing: {
        formFieldType: 'number',
        key: 'otherBorrowing',
        displayPriority: '9.4',
        label: 'Others',
        info: 'Others includes the sum of all other types of loans',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    receivablePTax: {
        formFieldType: 'number',
        key: 'receivablePTax',
        displayPriority: '10.1',
        label: 'Receivables for Property Tax',
        info: 'Receivables for Property Tax includes total amounts due towards property taxes',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    receivableFee: {
        formFieldType: 'number',
        key: 'receivableFee',
        displayPriority: '10.2',
        label: 'Receivables for Fee and User Charges',
        info: 'Receivables for Fee and User Chargesincludes total amounts due towards fee and user charges',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    otherReceivable: {
        formFieldType: 'number',
        key: 'otherReceivable',
        displayPriority: '10.3',
        label: 'Other Receivables',
        info: 'Other Receivables shall include any other amount due for taxes, goods sold or services rendered by ULB',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    totalReceivable: {
        formFieldType: 'number',
        key: 'totalReceivable',
        displayPriority: '10',
        label: 'Total Receivables',
        info: 'Total Receivables is the sum of total amounts due for taxes, goods sold or services rendered by ULB',
        required: true,
        year: 8,
        validation: 'sum',
        logic: ['10.1', '10.2', '10.3'],
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    totalCashAndBankBal: {
        formFieldType: 'number',
        key: 'totalCashAndBankBal',
        displayPriority: '11',
        label: 'Total Cash and Bank Balance',
        info: 'Total Cash & Bank Balance shall include cash held by the ULB and any money held in any bank/post office by the ULB (including municipal fund, special fund and grant funds)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: -999999999999999,
        max: 999999999999999,
        decimal: ''
    },
    coverageOfWs: {
        formFieldType: 'number',
        key: 'coverageOfWs',
        displayPriority: 1,
        label: 'Coverage of water supply connections (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    perCapitaOfWs: {
        formFieldType: 'number',
        key: 'perCapitaOfWs',
        displayPriority: 2,
        label: 'Per capita supply of water(lpcd)',
        info: '',
        placeholder: 'litres per capita per day (lpcd)|Range(0-999)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 999,
        decimal: 2,
        warning: { "value": 135, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 135 lpcd' }
    },
    extentOfMeteringWs: {
        formFieldType: 'number',
        key: 'extentOfMeteringWs',
        displayPriority: 3,
        label: 'Extent of metering of water connections (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfNonRevenueWs: {
        formFieldType: 'number',
        key: 'extentOfNonRevenueWs',
        displayPriority: 4,
        label: 'Extent of non-revenue water (NRW) (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    continuityOfWs: {
        formFieldType: 'number',
        key: 'continuityOfWs',
        displayPriority: 5,
        label: 'Continuity of water supplied (hours)',
        info: '',
        placeholder: 'Hours per day|Range(0-24)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 24,
        decimal: 0,
    },
    efficiencyInRedressalCustomerWs: {
        formFieldType: 'number',
        key: 'efficiencyInRedressalCustomerWs',
        displayPriority: 6,
        label: 'Efficiency in redressal of customer complaints related to water supply (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 80, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 80 lpcd' }
    },
    qualityOfWs: {
        formFieldType: 'number',
        key: 'qualityOfWs',
        displayPriority: 7,
        label: 'Quality of water supplied (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    costRecoveryInWs: {
        formFieldType: 'number',
        key: 'costRecoveryInWs',
        displayPriority: 8,
        label: 'Cost recovery in water supply service (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    efficiencyInCollectionRelatedWs: {
        formFieldType: 'number',
        key: 'efficiencyInCollectionRelatedWs',
        displayPriority: 9,
        label: 'Efficiency in collection of water supply-related charges (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 90, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 90 lpcd' }
    },
    coverageOfToiletsSew: {
        formFieldType: 'number',
        key: 'coverageOfToiletsSew',
        displayPriority: 10,
        label: 'Coverage of toilets (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    coverageOfSewNet: {
        formFieldType: 'number',
        key: 'coverageOfSewNet',
        displayPriority: 11,
        label: 'Coverage of sewerage network (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    collectionEfficiencySew: {
        formFieldType: 'number',
        key: 'collectionEfficiencySew',
        displayPriority: 12,
        label: 'Collection efficiency of sewerage network (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    adequacyOfSew: {
        formFieldType: 'number',
        key: 'adequacyOfSew',
        displayPriority: 13,
        label: 'Adequacy of sewerage treatment capacity (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    qualityOfSew: {
        formFieldType: 'number',
        key: 'qualityOfSew',
        displayPriority: 14,
        label: 'Quality of sewerage treatment (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfReuseSew: {
        formFieldType: 'number',
        key: 'extentOfReuseSew',
        displayPriority: 15,
        label: 'Extent of reuse and recycling of sewage (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    efficiencyInRedressalCustomerSew: {
        formFieldType: 'number',
        key: 'efficiencyInRedressalCustomerSew',
        displayPriority: 16,
        label: 'Efficiency in redressal of customer complaints related to sewerage (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfCostWaterSew: {
        formFieldType: 'number',
        key: 'extentOfCostWaterSew',
        displayPriority: 17,
        label: 'Extent of cost recovery in waste water management (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    efficiencyInCollectionSew: {
        formFieldType: 'number',
        key: 'efficiencyInCollectionSew',
        displayPriority: 18,
        label: 'Efficiency in collection of sewage water charges (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 90, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 90 lpcd' }
    },
    householdLevelCoverageLevelSwm: {
        formFieldType: 'number',
        key: 'householdLevelCoverageLevelSwm',
        displayPriority: 19,
        label: 'Household level coverage (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    efficiencyOfCollectionSwm: {
        formFieldType: 'number',
        key: 'efficiencyOfCollectionSwm',
        displayPriority: 20,
        label: 'Efficiency of collection of municipal solid waste (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfSegregationSwm: {
        formFieldType: 'number',
        key: 'extentOfSegregationSwm',
        displayPriority: 21,
        label: 'Extent of segregation of municipal solid waste (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfMunicipalSwm: {
        formFieldType: 'number',
        key: 'extentOfMunicipalSwm',
        displayPriority: 22,
        label: 'Extent of municipal solid waste recovered (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 80, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 80 lpcd' }
    },
    extentOfScientificSolidSwm: {
        formFieldType: 'number',
        key: 'extentOfScientificSolidSwm',
        displayPriority: 23,
        label: 'Extent of scientific disposal of municipal solid waste (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    extentOfCostInSwm: {
        formFieldType: 'number',
        key: 'extentOfCostInSwm',
        displayPriority: 24,
        label: 'Extent of cost recovery in SWM services (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    efficiencyInCollectionSwmUser: {
        formFieldType: 'number',
        key: 'efficiencyInCollectionSwmUser',
        displayPriority: 25,
        label: 'Efficiency in collection of SWM user charges (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 90, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 90 lpcd' }
    },
    efficiencyInRedressalCustomerSwm: {
        formFieldType: 'number',
        key: 'efficiencyInRedressalCustomerSwm',
        displayPriority: 26,
        label: 'Efficiency in redressal of customer complaints related to SWM (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
        warning: { "value": 80, "condition": "gt", "message": 'Please note that the entered value exceeds the threshold of 80 lpcd' }
    },
    coverageOfStormDrainage: {
        formFieldType: 'number',
        key: 'coverageOfStormDrainage',
        displayPriority: 27,
        label: 'Coverage of storm water drainage network (%)',
        info: '',
        placeholder: 'Percent|Range(0-100)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 100,
        decimal: 2,
    },
    incidenceOfWaterLogging: {
        formFieldType: 'number',
        key: 'incidenceOfWaterLogging',
        displayPriority: 28,
        label: 'Incidence of water logging',
        info: '',
        placeholder: 'Nos. per year|Range(0-9999)',
        required: true,
        year: 8,
        validation: '',
        logic: '',
        min: 0,
        max: 9999,
        decimal: 0,
    }
}

class tabsUpdationService {

    constructor(xviFcForm1Table) {
        this.detail = { ...xviFcForm1Table };
    }
    async getDataForDemographicDataTab(formType) {
        let form2 = [{ ...this.detail.yearOfSlb }];
        let form1 = [
            { ...this.detail.nameOfUlb },
            { ...this.detail.nameOfState },
            { ...this.detail.pop2011 },
            { ...this.detail.popApril2024 },
            { ...this.detail.areaOfUlb },
            { ...this.detail.yearOfElection },
            { ...this.detail.isElected },
            { ...this.detail.yearOfConstitution },
        ];
        return formType == "form1" ? form1 : formType == "form2" ? form1.concat(form2) : [];
    }
    async getDataForfinancialData(formType) {
        let form1 = [
            { ...this.detail.sourceOfFd },
            { ...this.detail.taxRevenue },
            { ...this.detail.feeAndUserCharges },
            { ...this.detail.interestIncome },
            { ...this.detail.otherIncome },
            { ...this.detail.totOwnRevenue },
            { ...this.detail.centralGrants },
            { ...this.detail.otherGrants },
            { ...this.detail.totalGrants },
            { ...this.detail.assignedRevAndCom },
            { ...this.detail.otherRevenue },
            { ...this.detail.totalRevenue },
            { ...this.detail.establishmentExp },
            { ...this.detail.oAndmExp },
            { ...this.detail.interestAndfinacialChar },
            { ...this.detail.otherRevenueExp },
            { ...this.detail.totalRevenueExp },
            { ...this.detail.capExp },
            { ...this.detail.totalExp },
            { ...this.detail.grossBorrowing },
        ];
        let form2 = [
            { ...this.detail.pTax },
            { ...this.detail.otherTax },
            { ...this.detail.rentalIncome },
            { ...this.detail.centralSponsoredScheme },
            { ...this.detail.unionFinanceGrants },
            { ...this.detail.sfcGrants },
            { ...this.detail.grantsOtherThanSfc },
            { ...this.detail.grantsWithoutState },
            { ...this.detail.salaries },
            { ...this.detail.pension },
            { ...this.detail.otherExp },
            { ...this.detail.adExp },
            { ...this.detail.centralStateBorrow },
            { ...this.detail.bonds },
            { ...this.detail.bankAndFinancial },
            { ...this.detail.otherBorrowing },
            { ...this.detail.receivablePTax },
            { ...this.detail.receivableFee },
            { ...this.detail.otherReceivable },
            { ...this.detail.totalReceivable },
            { ...this.detail.totalCashAndBankBal },
        ];
        return formType == "form1" ? form1 : formType == "form2" ? form1.concat(form2) : [];
    }
    async getDataForAccountingPractices() {
        return [
            { ...this.detail.accSystem },
            { ...this.detail.accProvision },
            { ...this.detail.accInCashBasis },
            { ...this.detail.fsTransactionRecord },
            { ...this.detail.fsPreparedBy },
            { ...this.detail.revReceiptRecord },
            { ...this.detail.expRecord },
            { ...this.detail.accSoftware },
            { ...this.detail.onlineAccSysIntegrate },
            { ...this.detail.muniAudit },
            { ...this.detail.totSanction },
            { ...this.detail.totVacancy },
            { ...this.detail.accPosition },
        ];
    }
    async getDataForUploadDoc() {
        return [
            { ...this.detail.auditedAnnualFySt }
        ];
    }
    async getDataForServiceLevelBenchmark() {
        return [
            { ...this.detail.coverageOfWs },
            { ...this.detail.perCapitaOfWs },
            { ...this.detail.extentOfMeteringWs },
            { ...this.detail.extentOfNonRevenueWs },
            { ...this.detail.continuityOfWs },
            { ...this.detail.efficiencyInRedressalCustomerWs },
            { ...this.detail.qualityOfWs },
            { ...this.detail.costRecoveryInWs },
            { ...this.detail.efficiencyInCollectionRelatedWs },
            { ...this.detail.coverageOfToiletsSew },
            { ...this.detail.coverageOfSewNet },
            { ...this.detail.collectionEfficiencySew },
            { ...this.detail.adequacyOfSew },
            { ...this.detail.qualityOfSew },
            { ...this.detail.extentOfReuseSew },
            { ...this.detail.efficiencyInRedressalCustomerSew },
            { ...this.detail.extentOfCostWaterSew },
            { ...this.detail.efficiencyInCollectionSew },
            { ...this.detail.householdLevelCoverageLevelSwm },
            { ...this.detail.efficiencyOfCollectionSwm },
            { ...this.detail.extentOfSegregationSwm },
            { ...this.detail.extentOfMunicipalSwm },
            { ...this.detail.extentOfScientificSolidSwm },
            { ...this.detail.extentOfCostInSwm },
            { ...this.detail.efficiencyInCollectionSwmUser },
            { ...this.detail.efficiencyInRedressalCustomerSwm },
            { ...this.detail.coverageOfStormDrainage },
            { ...this.detail.incidenceOfWaterLogging },
        ];
    }
}

module.exports.keyDetailsForm1 = keyDetailsForm1;
module.exports.keyDetailsForm2 = keyDetailsForm2;
module.exports.tabsUpdationService = tabsUpdationService;