const { years } = require("../../service/years")
const fiscalRankingFormJson = () => {
  return {
    goverPar: {
      normalData: {
        key: 'normalData',
        label: '',
        yearData: [
          {
            label: 'ULB website URL link where Copy of Audited Annual Accounts of FY 2019-20  to FY 2020-21 are available',
            key: 'webUrlAnnual',
            postion: '1',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "url",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'text'
          },
          {
            label: 'Is the property tax register GIS-based?',
            key: 'registerGis',
            postion: '2',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "radio",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'radio'
          },
          {
            label: 'Do you use accounting software?',
            key: 'accountStwre',
            postion: '3',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "radio",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'radio'
          }
        ]
      },
      auditReprtDate: {
        key: 'auditReprtDate',
        label: 'Own Revenue Details',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '1',
            value: '',
            date: null,
            file: '',
            min: '',
            max: '',
            required: true,
            formFieldType: "date",
            type: 'auditReprtDate',
            code: [],
            readonly: false,
            canShow: true,
            year: "607697074dff55e6c0be33ba",
            bottomText: ``,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '2',
            value: '',
            file: '',
            date: null,
            min: '',
            max: '',
            required: true,
            canShow: true,
            type: 'auditReprtDate',
            formFieldType: "date",
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: '',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '3',
            value: '',
            file: '',
            date: null,
            min: '',
            max: '',
            required: true,
            type: 'auditReprtDate',
            formFieldType: "date",
            code: [],
            readonly: false,
            canShow: true,
            year: "606aaf854dff55e6c075d219",
            bottomText: '',
            placeHolder: ''
          },
        ]
      },
      ownRevDetails: {
        key: 'ownRevDetails',
        label: 'Own Revenue Details',
        yearData: [
          {
            label: 'Total Own Revenue Arrears as on 31st March 2022',
            key: 'totalOwnRevenueArea',
            postion: '1',
            value: '',
            min: 0,
            max: 13,
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "number",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          }
        ]
      },
      ownRevenAmt: {
        key: 'ownRevenAmt',
        label: 'Own Revenue Collection Amount',
        yearData: [
          {
            label: 'FY 2021-22 - by Cash/Cheque/DD',
            key: 'fy_21_22_cash',
            postion: '2',
            value: '',
            min: 0,
            max: 13,
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'FY 2021-22 - by Online (UPI,Netbanking,Credit Card,Debit Card,others)',
            key: 'fy_21_22_online',
            postion: '3',
            value: '',
            min: 0,
            max: 13,
            required: true,
            year: "606aaf854dff55e6c075d219",
            readonly: false,
            canShow: true,
            formFieldType: "number",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          }
        ]
      },
      propertyDetails: {
        key: 'propertyDetails',
        label: 'Property Details',
        yearData: [
          {
            label: 'Number of Properties assessed/listed as per Property Tax Register (as on 1st April 2022)',
            key: 'property_tax_register',
            postion: '1',
            value: '',
            min: 0,
            max: 13,
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "number",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'Number of Properties exemt from paying Property Tax (as on 1st April 2022)',
            key: 'paying_property_tax',
            postion: '2',
            value: '',
            min: 0,
            max: 13,
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "number",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'Number of Properties for which Property Tax has been paid  (for FY 2021-22)',
            key: 'paid_property_tax',
            postion: '3',
            value: '',
            min: 0,
            max: 13,
            required: true,
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
        ]
      },
    },
    revenueMob: {
      totalRecActual: {
        key: 'totalRecActual',
        label: 'Total Receipts (Actual)',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of FY 2021-22`,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of FY 2021-22 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of FY 2022-23 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            canShow: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            bottomText: '',
            placeHolder: ''
          },
        ]
      },
      totalRcptWaterSupply: {  /// new add
        key: 'totalRcptWaterSupply',
        label: 'Total Receipts (Actual) for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of FY 2020-21 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of FY 2021-22 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of FY 2022-23 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            bottomText: '',
            placeHolder: ''
          },
        ]
      },
      totalRcptSanitation: {  /// new add
        key: 'totalRcptSanitation',
        label: 'Total Receipts (Actual) for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of FY 2020-21 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of FY 2021-22 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of FY 2022-23 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            bottomText: ' ',
            placeHolder: ''
          },
        ]
      },
      totalRecBudgetEst: {
        key: 'totalRecBudgetEst',
        label: 'Total Receipts (Budget Estimate)',
        yearData: [
          {
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of FY 2021-22 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of FY 2022-23 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            bottomText: ' ',
            placeHolder: ''
          },
        ]
      },
      totalOwnRevenues: {
        key: 'totalOwnRevenues',
        label: 'Total Own Revenues ',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            canShow: true,
            year: "63735a5bd44534713673c1ca",
            formFieldType: "number",
            bottomText: `to be taken from AuditedAnnual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            year: "607697074dff55e6c0be33ba",
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            canShow: true,
            year: "606aadac4dff55e6c075c507",
            formFieldType: "number",
            bottomText: 'to be taken from AuditedAnnual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            canShow: true,
            year: "606aaf854dff55e6c075d219",
            formFieldType: "number",
            bottomText: ' ',
            placeHolder: ''
          },
        ]
      },
      totalPropTaxRevenue: {
        key: 'totalPropTaxRevenue',
        label: 'Total Property Tax Revenue ',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalProperty',
            year: "63735a5bd44534713673c1ca",
            code: ['11001'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalProperty',
            code: ['11001'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['11001'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['11001'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aaf854dff55e6c075d219",
            bottomText: ' ',
            placeHolder: ''
          }
        ]
      },
      totalTaxRevWaterSupply: {
        key: 'totalTaxRevWaterSupply',
        label: 'Total tax Revenue for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            year: years["2018-19"],
            code: [11002],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            canShow: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from Audited Annual Budget of FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalTaxRevSanitation: {
        key: 'totalTaxRevSanitation',
        label: 'Total Tax Revenue for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            year: years["2018-19"],
            code: [11003],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [11003],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [11003],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: ' ',
            placeHolder: ''
          }
        ]
      },
      totalFeeChrgWaterSupply: {
        key: 'totalFeeChrgWaterSupply',
        label: 'Total Fee&User Charge for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            year: years["2018-19"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from Audited Annual Budget of FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalFeeChrgSanitation: {
        key: 'totalFeeChrgSanitation',
        label: 'Total Fee&User Charge for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            year: years["2018-19"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from Audited Annual Budget of FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            formFieldType: "number",
            canShow: true,
            year: years["2019-20"],
            bottomText: `to be taken from Audited Annual Budget of FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Budget of FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from Audited Annual Budget of FY 2021-22 ',
            placeHolder: ''
          }
        ]
      }
    },
    expPerf: {
      totalCaptlExp: {
        key: 'totalCaptlExp',
        label: 'Total Capital Expenditure',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            year: years["2018-19"],
            code: ["410", "412"],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: ["410", "412"],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: ["410", "412"],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: '',
            placeHolder: ''
          }
        ]
      },
      totalCaptlExpWaterSupply: {
        key: 'totalCaptlExpWaterSupply',
        label: 'Total Capital Expenditure for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            year: years["2018-19"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalCaptlExpSanitation: {
        key: 'totalCaptlExpSanitation',
        label: 'Total Capital Expenditure for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            year: years["2018-19"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalOmExp: {
        key: 'totalOmExp',
        label: 'Total O & M Expenditure',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            year: years["2018-19"],
            code: ['230'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2018-19 `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: ['230'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: ['230'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: ['230'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: ' ',
            placeHolder: ''
          }
        ]
      },
      totalOMCaptlExpWaterSupply: {
        key: 'totalOMCaptlExpWaterSupply',
        label: 'O & M Expenditure for Water Supply',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalOMCaptlExpSanitation: {
        key: 'totalOMCaptlExpSanitation',
        label: 'O & M Expenditure for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2019-20"],
            bottomText: `to be taken from  from I&E statement of Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            formFieldType: "number",
            canShow: true,
            year: years["2021-22"],
            bottomText: 'to be taken from  from I&E statement of Audited Annual Accounts for FY 2021-22 ',
            placeHolder: ''
          }
        ]
      },
      totalRevExp: {
        key: 'totalRevExp',
        label: 'Total Revenue Expenditure',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'totalRevExp_19-20',
            postion: '4',
            value: '',
            file: '',
            min: '',
            max: '',
            required: true,
            type: 'totalRevExp',
            year: years["2019-20"],
            code: ['210', '220', '230', '240', '200'],
            readonly: false,
            formFieldType: "number",
            canShow: true,
            bottomText: `to be taken from Audited Annual Accounts for FY 2019-20 `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: ['210', '220', '230', '240', '200'],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from Audited Annual Accounts for FY 2020-21 ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            value: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "number",
            year: years["2021-22"],
            bottomText: ' ',
            placeHolder: ''
          }
        ]
      },
    },
    uploadFyDoc: {
      guidanceNotes: {
        key: 'guidanceNotes',
        label: 'Guidance Notes:',
        yearData: [
          {
            title: '',
            pos: '1',
            desc: `Audited Annual Accounts should include: Income and Expenditure Statement, Balance Sheet, Schedules to IES and BS, and Auditor's Report.`
          },
          {
            title: '',
            pos: '2',
            desc: `Annual Budgets should be the detailed final approved version and should be in English language.`
          },
          {
            title: '',
            pos: '3',
            desc: `Files uploaded should be in PDF only and file size should not exceed 5MB.`
          }
        ]
      },
      appAnnualBudget: {
        key: 'appAnnualBudget',
        label: 'Copy of Approved Annual Budget in English',
        yearData: [
          {
            label: 'FY 2020-21',
            key: 'appAnnualBudget_2020-21',
            postion: '1',
            value: '',
            min: 0,
            max: 13,
            required: true,
            type: 'appAnnualBudget',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            canShow: true,
            formFieldType: "file",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'Maximum Size  5MB (pdf files only)',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'appAnnualBudget_2021-22',
            postion: '2',
            value: '',
            min: 0,
            max: 13,
            required: true,
            canShow: true,
            type: 'appAnnualBudget',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            formFieldType: "file",
            year: years["2021-22"],
            bottomText: 'Maximum Size  5MB (pdf files only) ',
            placeHolder: ''
          },
          {
            label: 'FY 2022-23',
            key: 'appAnnualBudget_2022-23',
            postion: '3',
            value: '',
            min: 0,
            max: 13,
            required: true,
            type: 'appAnnualBudget',
            formFieldType: "file",
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            canShow: true,
            year: "606aafb14dff55e6c075d3ae",
            bottomText: 'Maximum Size  5MB (pdf files only) ',
            placeHolder: ''
          }
        ]
      },
      auditedAnnualFySt: {
        key: 'auditedAnnualFySt',
        label: 'Copy of Audited Annual Financial Statements in English',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'auditedAnnualFySt_2018-19',
            postion: '1',
            value: '',
            file: {
              name: "",
              url: ""
            },
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            year: years["2018-19"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "file",
            bottomText: `Maximum Size  5MB (pdf files only) `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'auditedAnnualFySt_2019-20',
            postion: '1',
            value: '',
            file: {
              name: "",
              url: ""
            },
            min: '',
            max: '',
            required: true,
            type: 'auditedAnnualFySt',
            year: years["2019-20"],
            code: [],
            readonly: false,
            canShow: true,
            formFieldType: "file",
            bottomText: `Maximum Size  5MB (pdf files only)`,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'auditedAnnualFySt_2020-21',
            postion: '2',
            value: '',
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            canShow: true,
            formFieldType: "file",
            year: "606aadac4dff55e6c075c507",
            bottomText: 'Maximum Size  5MB (pdf files only) ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'auditedAnnualFySt_2021-22',
            postion: '3',
            value: '',
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            canShow: true,
            formFieldType: "file",
            year: years["2021-22"],
            bottomText: 'Maximum Size  5MB (pdf files only) ',
            placeHolder: ''
          }
        ]
      },
    }
  }
}
function getInputKeysByType(formType, type, label, dataSource = null, position, min = "", max = "") {
  return {
    label: label,
    max: max,
    min: min,
    placeHolder: "",
    postion: position,
    modelName: dataSource, // USER | LEDGER
    formFieldType: formType, // text | number | radio-toggle | file
    required: true,
    type: type,
    canShow: true
  }
}

let fiscalRankingTabs = () => {
  return [{
    "key": "basicUlbDetails",
    "icon": "",
    "text": "",
    "label": "Basic ULB Details",
    "id": "s1",
    "displayPriority": 1
  },
  {
    "key": "conInfo",
    "icon": "",
    "text": "",
    "label": "Contact information",
    "id": "s2",
    "displayPriority": 2,
  },
  {
    "key": "revenueMob",
    "icon": "",
    "text": "",
    "label": "Revenue Mobilization Parameters",
    "id": "s3",
    "displayPriority": 3
  },
  {
    "key": "expPerf",
    "icon": "",
    "text": "",
    "label": "Expenditure Performance Parameters",
    "id": "s4",
    "displayPriority": 4,
  },
  {
    "key": "goverPar",
    "icon": "",
    "text": "",
    "label": "Fiscal Governance Parameters",
    "id": "s5",
    "displayPriority": 5,
  },
  {
    "key": "uploadFyDoc",
    "icon": "",
    "text": "",
    "label": "Upload Financial Documents",
    "id": "s6",
    "displayPriority": 6
  },
  {
    "key": "selDec",
    "icon": "",
    "text": "",
    "label": "Self Declaration",
    "id": "s7",
    "displayPriority": 7
  }]
}
module.exports.fiscalRankingTabs = fiscalRankingTabs;
module.exports.fiscalRankingFormJson = fiscalRankingFormJson;
module.exports.getInputKeysByType = getInputKeysByType;