const fiscalRankingFormJson = () => {
  return {
    goverPar: {
      normalData: {
        key: 'normalData',
        label: '',
        yearData: [
          {
            label: 'ULB website URL link where Copy of Audited Annual Accounts of FY 2019-20  to FY 2020-21 are available',
            key: 'webUrlAnnual',
            postion: '1',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'text'
          },
          {
            label: 'Is the property tax register GIS-based?',
            key: 'registerGis',
            postion: '2',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'radio'
          },
          {
            label: 'Do you use accounting software?',
            key: 'accountStwre',
            postion: '3',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'radio'
          }
        ]
      },
      auditReprtDate: {
        key: 'auditReprtDate',
        label: 'Own Revenue Details',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '1',
            amount: '',
            date: null,
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'auditReprtDate',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: ``,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '2',
            amount: '',
            file: '',
            date: null,
            min: 0,
            max: 13,
            required: true,
            type: 'auditReprtDate',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: '',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '3',
            amount: '',
            file: '',
            date: null,
            min: 0,
            max: 13,
            required: true,
            type: 'auditReprtDate',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: '',
            placeHolder: ''
          },
        ]
      },
      ownRevDetails: {
        key: 'ownRevDetails',
        label: 'Own Revenue Details',
        yearData: [
          {
            label: 'Total Own Revenue Arrears as on 31st March 2022',
            key: 'totalOwnRevenueArea',
            postion: '1',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          }
        ]
      },
      ownRevenAmt: {
        key: 'ownRevenAmt',
        label: 'Own Revenue Collection Amount',
        yearData: [
          {
            label: 'FY 2021-22 - by Cash/Cheque/DD',
            key: 'fy_21_22_cash',
            postion: '2',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'FY 2021-22 - by Online (UPI,Netbanking,Credit Card,Debit Card,others)',
            key: 'fy_21_22_online',
            postion: '3',
            value: '',
            min: '',
            max: '',
            required: true,
            year: "606aaf854dff55e6c075d219",
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          }
        ]
      },
      propertyDetails: {
        key: 'propertyDetails',
        label: 'Property Details',
        yearData: [
          {
            label: 'Number of Properties assessed/listed as per Property Tax Register (as on 1st April 2022)',
            key: 'property_tax_register',
            postion: '1',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'Number of Properties exemt from paying Property Tax (as on 1st April 2022)',
            key: 'paying_property_tax',
            postion: '2',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
          {
            label: 'Number of Properties for which Property Tax has been paid  (for FY 2021-22)',
            key: 'paid_property_tax',
            postion: '3',
            value: '',
            min: '',
            max: '',
            required: true,
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            type: '',
            bottomText: ``,
            placeHolder: '',
            input: 'number'
          },
        ]
      },
    },
    revenueMob: {
      totalRecActual: {
        key: 'totalRecActual',
        label: 'Total Receipts (Actual)',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptActl',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
        ]
      },
      totalRcptWaterSupply: {  /// new add
        key: 'totalRcptWaterSupply',
        label: 'Total Receipts (Actual) for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptWaterSupply',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
        ]
      },
      totalRcptSanitation: {  /// new add
        key: 'totalRcptSanitation',
        label: 'Total Receipts (Actual) for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
        ]
      },
      totalRecBudgetEst: {
        key: 'totalRecBudgetEst',
        label: 'Total Receipts (Budget Estimate)',
        yearData: [
          {
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalRcptBudget',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
        ]
      },
      totalOwnRevenues: {
        key: 'totalOwnRevenues',
        label: 'Total Own Revenues ',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            year: "63735a5bd44534713673c1ca",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            year: "607697074dff55e6c0be33ba",
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['110', '130', '140', '150', '180'],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
        ]
      },
      totalPropTaxRevenue: {
        key: 'totalPropTaxRevenue',
        label: 'Total Property Tax Revenue ',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalProperty',
            year: "63735a5bd44534713673c1ca",
            code: ['11001'],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalProperty',
            code: ['11001'],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['11001'],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOwnRvnue',
            code: ['11001'],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalTaxRevWaterSupply: {
        key: 'totalTaxRevWaterSupply',
        label: 'Total tax Revenue for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            year: "63735a5bd44534713673c1ca",
            code: [11002],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevWaterSupply',
            code: [11002],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalTaxRevSanitation: {
        key: 'totalTaxRevSanitation',
        label: 'Total Tax Revenue for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            year: "63735a5bd44534713673c1ca",
            code: [11003],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [11003],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [11003],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalTaxRevSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalFeeChrgWaterSupply: {
        key: 'totalFeeChrgWaterSupply',
        label: 'Total Fee&User Charge for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgWaterSupply',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalFeeChrgSanitation: {
        key: 'totalFeeChrgSanitation',
        label: 'Total Fee&User Charge for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      }
    },
    expPerf: {
      totalCaptlExp: {
        key: 'totalCaptlExp',
        label: 'Total Capital Expenditure',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExp',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalCaptlExpWaterSupply: {
        key: 'totalCaptlExpWaterSupply',
        label: 'Total Capital Expenditure for Water Supply',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalCaptlExpSanitation: {
        key: 'totalCaptlExpSanitation',
        label: 'Total Capital Expenditure for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalOmExp: {
        key: 'totalOmExp',
        label: 'Total O & M Expenditure',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'FY2018-19',
            postion: '1',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            year: "63735a5bd44534713673c1ca",
            code: [230],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: [230],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: [230],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOmExp',
            code: [230],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalOMCaptlExpWaterSupply: {
        key: 'totalOMCaptlExpWaterSupply',
        label: 'O & M Expenditure for Water Supply',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalCaptlExpWaterSupply',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalOMCaptlExpSanitation: {
        key: 'totalOMCaptlExpSanitation',
        label: 'O & M Expenditure for Sanitation/Sewerage',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'FY2019-20',
            postion: '2',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "607697074dff55e6c0be33ba",
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      totalRevExp: {
        key: 'totalRevExp',
        label: 'Total Revenue Expenditure',
        yearData: [
          {
            label: 'FY 2019-20',
            key: 'totalRevExp_19-20',
            postion: '4',
            amount: '',
            file: '',
            min: '',
            max: '',
            required: true,
            type: 'totalRevExp',
            year: "607697074dff55e6c0be33ba",
            code: ['210', '220', '230', '240', '200'],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'FY2020-21',
            postion: '3',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: ['210', '220', '230', '240', '200'],
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'FY2021-22',
            postion: '4',
            amount: '',
            file: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalOMCaptlExpSanitation',
            code: [],
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
    },
    uploadFyDoc: {
      guidanceNotes: {
        key: 'guidanceNotes',
        label: 'Guidance Notes:',
        yearData: [
          {
            title: '',
            pos: '1',
            desc: `Audited Annual Accounts should include: Income and Expenditure Statement, Balance Sheet, Schedules to IES and BS, and Auditor's Report.`
          },
          {
            title: '',
            pos: '2',
            desc: `Annual Budgets should be the detailed final approved version and should be in English language.`
          },
          {
            title: '',
            pos: '3',
            desc: `Files uploaded should be in PDF only and file size should not exceed 5MB.`
          }
        ]
      },
      appAnnualBudget: {
        key: 'appAnnualBudget',
        label: 'Copy of Approved Annual Budget in English',
        yearData: [
          {
            label: 'FY 2020-21',
            key: 'appAnnualBudget_2020-21',
            postion: '2',
            amount: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'appAnnualBudget_2021-22',
            postion: '3',
            amount: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2022-23',
            key: 'appAnnualBudget_2022-23',
            postion: '4',
            amount: '',
            min: 0,
            max: 13,
            required: true,
            type: 'totalFeeChrgSanitation',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            year: "606aafb14dff55e6c075d3ae",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
      auditedAnnualFySt: {
        key: 'auditedAnnualFySt',
        label: 'Copy of Audited Annual Financial Statements in English',
        yearData: [
          {
            label: 'FY 2018-19',
            key: 'auditedAnnualFySt_2018-19',
            postion: '1',
            amount: '',
            file: {
              name: "",
              url: ""
            },
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            year: "63735a5bd44534713673c1ca",
            code: [],
            readonly: false,
            bottomText: `to be taken from approved Annual Budget of `,
            placeHolder: ''
          },
          {
            label: 'FY 2019-20',
            key: 'auditedAnnualFySt_2019-20',
            postion: '1',
            amount: '',
            file: {
              name: "",
              url: ""
            },
            min: '',
            max: '',
            required: true,
            type: 'auditedAnnualFySt',
            year: "607697074dff55e6c0be33ba",
            code: [],
            readonly: false,
            bottomText: `Maximum Size  5MB (pdf files only)`,
            placeHolder: ''
          },
          {
            label: 'FY 2020-21',
            key: 'auditedAnnualFySt_2020-21',
            postion: '2',
            amount: '',
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            year: "606aadac4dff55e6c075c507",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          },
          {
            label: 'FY 2021-22',
            key: 'auditedAnnualFySt_2021-22',
            postion: '3',
            amount: '',
            min: 0,
            max: 13,
            required: true,
            type: 'auditedAnnualFySt',
            code: [],
            file: {
              name: "",
              url: ""
            },
            readonly: false,
            year: "606aaf854dff55e6c075d219",
            bottomText: 'to be taken from approved Annual Budget of ',
            placeHolder: ''
          }
        ]
      },
    }
  }
}
module.exports.fiscalRankingFormJson = fiscalRankingFormJson;