require("./dbConnect");
const propertyTaxOpMapper = new Schema(
    {
        ptoId: { type: Schema.Types.ObjectId, ref: "PropertyTaxOp", required: true },
        ulb: { type: Schema.Types.ObjectId, ref: "Ulb", required: true },
        year: { type: Schema.Types.ObjectId, ref: "Year", required: true },
        value: { type: Schema.Types.Mixed, default: null },
        date: { type: Date, default: null }, // audit date
        status: {
            type: String,
            default: "PENDING",
            enum: {
                values: ["PENDING", "APPROVED", "REJECTED", "NA"],
                message: "ERROR: STATUS BE EITHER 'PENDING'/ 'APPROVED' / 'REJECTED'",
            },
        },
        isActive: { type: Boolean, default: 1 },
        type: {
            type: String,
            enum: {
                values: [
                    "notificationPropertyTax",
                    "notificationAdoptionDate",
                    "notificationIssuedBy",
                    "notificationFile",
                    "dmdIncludingCess",
                    "dmdexcludingCess",
                    "taxTypeDemandType",
                    "taxTypeDemand",
                    "cessDemandType",
                    "cessDemand",
                    "doesUserChargesDmnd",
                    "userChargesDmndWater",
                    "userChargesDmndSewerage",
                    "userChargesDmndSWM",
                    "userChargesDmndDrainage",
                    "collectIncludingCess",
                    "collectExcludingCess",
                    "taxTypeCollectionType",
                    "taxTypeCollection",
                    "cessCollectType",
                    "cessCollect",
                    "userChargesColWater",
                    "userChargesColSewerage",
                    "userChargesColSWM",
                    "userChargesColDrainage",
                    "totalMappedPropertiesUlb",
                    "totalPropertiesTax",
                    "totalPropertiesTaxDm",
                    "totalPropertiesTaxDmCollected",
                    "resValuePropertyTaxDm",
                    "resNoPropertyTaxDm",
                    "resValuePropertyTaxCollected",
                    "resNoPropertyTaxCollected",
                    "comValuePropertyTaxDm",
                    "comNoPropertyTaxDm",
                    "comValuePropertyTaxCollected",
                    "comNoPropertyTaxCollected",
                    "indValuePropertyTaxDm",
                    "indNoPropertyTaxDm",
                    "indValuePropertyTaxCollected",
                    "indNoPropertyTaxCollected",
                    "govValuePropertyTaxDm",
                    "govNoPropertyTaxDm",
                    "govValuePropertyTaxCollected",
                    "govNoPropertyTaxCollected",
                    "insValuePropertyTaxDm",
                    "insNoPropertyTaxDm",
                    "insValuePropertyTaxCollected",
                    "insNoPropertyTaxCollected",
                    "otherValuePropertyType",
                    "otherValuePropertyTaxDm",
                    "otherNoPropertyTaxDm",
                    "otherValuePropertyTaxCollected",
                    "otherNoPropertyTaxCollected",
                    "noOfPropertiesPaidOnline",
                    "totalCollectionOnline",
                    "propertyTaxValuationDetails",
                    "propertyTaxCollectionBookCurrentDm",
                    "propertyTaxCollectionBookCurrentCol",
                    "propertyTaxCollectionBookCurrentArdm",
                    "propertyTaxCollectionBookCurrentArCol",
                    "propertyTaxCollectionBookCurrentTotalDm",
                    "propertyTaxCollectionBookCurrentTotalCol",
                    "notificationWaterCharges",
                    "notificationWaterChargesFile",
                    "WaterChrgDm",
                    "WaterChrgCol",
                    "waterChrgConnectionDm",
                    "waterChrgConnectionCol",
                    "resValueWaterChrgDm",
                    "resNoWaterChrgDm",
                    "resValueWaterChrgCollected",
                    "resNoWaterChrgCollected",
                    "comValueWaterChrgDm",
                    "comNoWaterChrgDm",
                    "comValueWaterChrgCollected",
                    "comNoWaterChrgCollected",
                    "indValueWaterChrgDm",
                    "indNoWaterChrgDm",
                    "indValueWaterChrgCollected",
                    "indNoWaterChrgCollected",
                    "othersValueWaterType",
                    "othersValueWaterChrgDm",
                    "othersNoWaterChrgDm",
                    "othersValueWaterChrgCollected",
                    "othersNoWaterChrgCollected",
                    "waterChrgTariffDetails",
                    "waterChrgCollectionBookCurrentDm",
                    "waterChrgCollectionBookCurrentCol",
                    "waterChrgCollectionBookCurrentArdm",
                    "waterChrgCollectionBookCurrentArCol",
                    "waterChrgCollectionBookCurrentTotalDm",
                    "waterChrgCollectionBookCurrentTotalCol",
                    "omCostDeleveryWater",
                    "omCostWaterService",
                    "doesColSewerageCharges",
                    "copyGazetteNotificationSewerage",
                    "totalSewergeChrgDm",
                    "totalSewergeChrgCol",
                    "totalSewergeConnectionDm",
                    "totalSewergeConnectionCol",
                    "resValueSewerageTaxDm",
                    "resNoSewerageTaxDm",
                    "resValueSewerageTaxCollected",
                    "resNoSewerageTaxCollected",
                    "comValueSewerageTaxDm",
                    "comNoSewerageTaxDm",
                    "comValueSewerageTaxCollected",
                    "comNoSewerageTaxCollected",
                    "indValueSewerageTaxDm",
                    "indNoSewerageTaxDm",
                    "indValueSewerageTaxCollected",
                    "indNoSewerageTaxCollected",
                    "otherValueSewerageType",
                    "otherValueSewerageTaxDm",
                    "otherNoSewerageTaxDm",
                    "otherValueSewerageTaxCollected",
                    "otherNoSewerageTaxCollected",
                    "SewerageChrgTarrifSheet",
                    "sewerageCollectionBookCurrentDm",
                    "sewerageCollectionBookCurrentCol",
                    "sewerageCollectionBookCurrentArdm",
                    "sewerageCollectionBookCurrentArCol",
                    "sewerageCollectionBookCurrentTotalDm",
                    "sewerageCollectionBookCurrentTotalCol",
                    "omCostDeleverySewerage",
                    "omCostSewerageService",
                    "signedPdf"
                ],
                message: "ERROR: STATUS BE EITHER",
            },
        },
        file: {
            name: { type: String },
            url: { type: String }
        },
        displayPriority: { type: Number, default: null },
        createdAt: { type: Date, default: Date.now() },
        modifiedAt: { type: Date, default: Date.now() },
    },
    { timestamp: { createdAt: "createdAt", updatedAt: "modifiedAt" } }
);
module.exports = mongoose.model("PropertyTaxOpMapper", propertyTaxOpMapper);


